# -*- coding: utf-8 -*-
"""Chap2-Hello-Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kRqeznVtDocbBKt2mTAmI6LZcz6GyyVX

# Introduction to Python

---

**Objectives**

1. Create and store variables
2. Work with built-in data types
3. Use arithmetic and comparison operators, including precedence.
4. Use singe, double, and triple quoted strings
5. Display values with built-in function ```print``` 
6. Prompt users with ```input``` function to get data
7. Convert text to integer values with built-in function ```int```
8. Use comparison operators and the ```if``` statement to decide to execute statement(s)
9. Use ```type``` to examine the data type

---

## Variables and Assignment Statements

Python expressions (e.g., 4+9) may contain **variables** which store values for later use in code.  For example the variable ```x``` can store the integer ```5```.  That is, we assignment the value ```5``` to the variable ```x``` by creating the **statement**  ```x=5```.
"""

x = 5

"""### Variable Names

A variable name (also called an __identifier__) can contain:
* letters
* digits (_Note_: cannot begin with digit)
* underscores

> Python is __case sensitive__ and therefore `total` is different from `Total`.
"""

total = 5
Total = 7
_total = 12
# 1st_total   invalid variable name

"""### Types
Every value has a __type__ (e.g., `int`, `float`).  To view the _value type_, use the `type` function.
"""

x = 1
type(x)

type(3.1415)

type('Hello')

type("Hello")

"Joe's"

'Joe\'s'

# Memory ID
id(x)

"""### Python Style Documentation

See https://www.python.org/dev/peps/pep-0008/

## Arithmetic

The following table summarizes arithmetic operations.

| Operation          | Operator | Example Expression |
|--------------------|----------|--------------------|
| Addition           | +        | 2 + 3              |
| Subtraction        | -        | 9 - 5              |
| Multiplication     | *        | 5 * 6              |
| Exponentiation     | **       | x ** y             |
| Division           | /        | 10 / 2             |
| Floor Division     | //       | 10 // 3            |
| Remainder (modulo) | %        | 9 % 5              |
"""

# Addtion
3 + 2

# Subtraction
3 - 2

# Multiplication
3 * 2

# Division
3 / 2

# Integer Division
3 // 2

# beware of negative numbers
# "selects integer to the left"
-27 // 4

# Exponentiation
3 ** 2

# Remainder
27 % 4

# Negative numbers produce different results
-27 % 4

"""### Grouping Expressions with Parentheses

Parentheses are used similar to mathematics.  Notice the following two expressions produce different results.

"""

2 * (3 + 4)
2 * 3 + 4

"""### Operator Precedence Rules
* PEMDAS Left to Right
* Exponents (Right to Left)
* `%, //` same as multiplication/division (Left to Right)

### Operand Types

What is the sum of an integer and a float?
* Mixed-type produce floats.
"""

a = 2
x = 3
y = a*x*x*x +7
y = a*x**3 + 7

"""# 2.4 Print function and Single- & Double-Quoted Strings

The built-in `print` function diplays its arguments as text.
"""

# Single quotes (often preferred)
print('Hello World')

"""You can use double quotes too."""

print("Hello World")



"""> Note, the quotes are not displayed.

### Comma-Separated List
Python will print each argument in the list separated by a space.
"""

print('Hello','World')
print('Hello '+'World')

print('3 + 2', '=','5')
print('3 + 2 =',3+2)

# NOTE: 1 space is added after each string.
# NOTE: Concatenation with + is deprecated.
print('3 + 2 = ' + '5')
print('3 + 2 = '+ str(3+2))

"""### Escape Sequences

A backslash (\\) is an __escape character__.  It and the character immediately following it form an __escape sequence__.

| Escape Sequence | Description         |
|-----------------|---------------------|
| \n              | Insert a new line   |
| \t              | Insert tab          |
| \\\             | Insert backslash    |
| \\'             | Insert single quote |
| \\"             | Insert double quote |
"""

print('Here is a line\n and then next\n\n')
print('Here we insert a \t tab')
print('To put \'single quotes\' in the string')
print('To put \"double quotes\" in the string')
print('Here is a backslash \\')

"""# 2.5 Triple-Quoted Strings


* Including Quotes (both single and double) in Strings
* Docstrings, document source


"""

print("Here is 'single quotes'. ")

print("""This is a string with "double quotes" inside.""")

"""# 2.6 Getting Input from the User

Basic I/O



### `input` always returns a string!

### Get an integer from user
Since `input` always returns a string, we must convert (cast) the input as an integer.  In particular,

```python
```



"""

#value = input('Enter an integer value: ')  # a string
#value = int(value)                         # now an integer

# or
value = int(input('Enter an integer value: '))
print('Twice the value is',2*value)

"""# 2.7 Decision Making: `if` statement and comparison operators

* Practical construct - Flow control
* Decision structure = Branching

**Boolean expressions** evaluate to TRUE or FALSE.  A **condition** is a Boolean expression.  For example,
"""

1 < 2

3 != 5

"""Conditions often use **comparison operators**, i.e., ```>, <, >=, <=, ==, !=```.  Be aware of the precedence of these operators, the first four have same precedence, but higher than the last two (which have the same precedence).  That is, ```<``` and ```>``` have the same precedence, which is higher than ```==```.  

Also, be aware of syntax errors such as ``` < = ```.  The correct syntax is ```<=```.

### ```if``` statements (branching structure)

The basic syntax of an ```if``` statement is:

```
if condition:
  code_block
```
Notice the colon (:) and the indentation.  

Here is an actual example,
"""

x = int(input('Enter first integer: '))
y = int(input('Enter second integer: '))

if x < y:
  print('Yes')

x = int(input('Enter first integer: '))
y = int(input('Enter second integer: '))

if x < y:
  print('Yes')
else:
  print('No')

"""# Homework (Due Sept. 8)

Chapter 2: 1 - 15

---
"""